services:


  prometheus:

    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml



  grafana:

    image: grafana/grafana

    container_name: grafana

    ports:
      - "3000:3000"



  sample-app:

    build:
      context: ./sample-app

    container_name: sample-app

    ports:
      - "8000:8000"

    volumes:
      - ./logs:/app/logs

  loki:
    image: grafana/loki:3.5.5
    container_name: loki

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/config.yml

    volumes:
      - ./loki/config.yml:/etc/loki/config.yml

  promtail:
    image: grafana/promtail:3.5.5
    container_name: promtail

    command: -config.file=/etc/promtail/config.yml

    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/sample-app

    depends_on:
      - loki
  
  alert-receiver:
    build:
      context: ./alert-receiver
    container_name: alert-receiver

    ports:
      - "8001:8000"

    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - LOKI_URL=http://loki:3100

    depends_on:
      - prometheus
      - loki

  alert-assistant:
    build:
      context: ./alert-assistant
    container_name: assistant
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - LOKI_URL=http://loki:3100
    depends_on:
      - prometheus
      - loki
